import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import axios from "axios";
import Image from "next/image";
import NavLogo from "../../public/nav-logo.svg";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <nav className="nav">
            <div className="nav__wrapper flex justify-between items-center py-2 px-4">
              <div>
                <Image src={NavLogo} alt="rasm yo" />
              </div>
              <ul className="nav__list flex gap-2">
                <li>
                  <Link href="/">
                    <span>Home</span>
                  </Link>
                </li>

                <li>
                  <Link href="/">
                    <span>About</span>
                  </Link>
                </li>
              </ul>
            </div>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
